### ISSUE TITLE
Secure Email Tracking Specification

### ISSUE THREAD

**Issue by Mai-L1** [Mai-L1/LoyaltyOne-Secure-Email#1]
**Implementation Check-list**

- [ ] MVP: dataLayer variable is initialized (before GTM code snippet)
- [ ] MVP: GTM code snippet is placed in \<head\>
- [ ] MVP: meta-data on Team Air Miles page is added

## Initializing the dataLayer and Installing GTM

A data layer is a JavaScript array which is used to store information and send information to the Google Tag Manager container.

**Please ensure the dataLayer is defined before the GTM container snippet. If the GTM snippet cannot find the dataLayer variable, then it will initialize an empty object.**

Include the dataLayer in the \<head> of each page

Below is an example of a dataLayer from airmiles.ca. Note in some digital properties, not all variables are available to be placed in the dataLayer or be relevant.

```
    var dataLayer = [{
       //GENERAL
       "pageName"          : pageName[pageName.length-1],
       "domainName"        : "airmiles.ca",
       "language"          : "en",
       "errorMessage"      : null,
                                
       "collectorNumber"   : '84032486711',
       "collectorLogin"    : "Level-1.9",
       "collectorTier"     : "ONYX"
    }];
```
  
### Adding the GTM Container Snippet
In the \<head>, below the dataLayer, include the following snippet:

```
<!-- Google Tag Manager & Optimize -->
<style>.async-hide { opacity: 0 !important} </style>
<script>
   (function(a,s,y,n,c,h,i,d,e){s.className+=' '+y;h.start=1*new Date;
   h.end=i=function(){s.className=s.className.replace(RegExp(' ?'+y),'')};
   (a[n]=a[n]||[]).hide=h;setTimeout(function(){i();h.end=null},c);h.timeout=c;
   })(window,document.documentElement,'async-hide','dataLayer',4000,
   {'GTM-PQGZ8WM':true}); //Optimize Account ID
</script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-76333024-1', 'auto'); // GA Account ID
  ga('require', 'GTM-PQGZ8WM'); //Optimize Account ID
</script>
<script>
   (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
   new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
   j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
   'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
   })(window,document,'script','dataLayer','GTM-W9P5KD');  // GTM Account ID
</script>
<!-- End Google Tag Manager & Optimize -->

```

Then, immediately following the opening \<body> tag, include this snippet:

```
    <!-- Google Tag Manager (noscript) -->
    <noscript>
       <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-W9P5KD"
       height="0" width="0" style="display:none;visibility:hidden"></iframe>
    </noscript>
    <!-- End Google Tag Manager (noscript) -->
```
